config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :create]
  resources :weapons, only: [:index, :create, :show, :destroy]
  resources :enemies, only: [:index, :create, :show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
    enum kind: [ :goblin, :orc, :demon, :dragon ]
    validates :level, numericality: {greater_than: 0, less_than_or_equal_to: 99}
    validates_presence_of :name, :power_base, :power_step, :level, :kind


    def current_power
        power_base + ((level -1) * power_step)
    end
end

app/models/user.rb
class User < ApplicationRecord
    enum kind: [ :knight, :wizard ]
    validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

    def title
        "#{self.kind} #{self.nickname} ##{self.level}"
    end
end

app/models/weapon.rb
class Weapon < ApplicationRecord

    validates :name, :description, :power_base, :power_step, :level, presence: true
    
    #this level show the power now of weapon
    def current_power
        (self.power_base + ((level - 1) * self.power_step))
    end

    def title
        "#{self.name} ##{self.level}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy, only: [:show, :update, :destroy]

  def index
    @enemies = Enemy.all
    respond_to do |format|
      format.html
      format.json { render json: @enemies }
    end
  end

  def create
    @enemy = Enemy.new(enemy_params)
    if @enemy.save
      render json: @enemy, status: :created
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @enemy }
    end
  end

  def update
    if @enemy.update(enemy_params)
      render json: @enemy, status: :ok
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @enemy.destroy
    head  204
  end

  private

  def enemy_params
    params.require(:enemy).permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:nickname, :kind, :level)
    end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def show
    @weapon = Weapon.find(params[:id])
    respond_to do |format|
      format.html # Renderiza o template show.html.erb
      format.json { render json: @weapon } # Responde com JSON
    end
  end


  def create
    @weapon = Weapon.create(weapon_params)
    redirect_to weapons_path, notice: 'Weapon was created successfully'
  end
  
  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy
    redirect_to weapons_path, notice: 'Weapon was successfully destroyed.'
  end

 

  private
    def weapon_params
      params.require(:weapon).permit(:name, :description, :power_base, :power_step, :level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

app/views/enemies/index.html.erb
<h1> Lista de Inimigos</h1>

<ul>
  <% @enemies.each do |enemy| %>
    <li>
      <p><strong>Nome:</strong> <%= enemy.name %></p>
      <p><strong>Kind:</strong> <%= enemy.kind %></p>
      <p><strong>Level:</strong> <%= enemy.level %></p> <!-- Correção aqui -->
      <p><strong>Power base:</strong> <%= enemy.power_base %></p>
      <p><strong>Power step:</strong> <%= enemy.power_step %></p>
    </li>
  <% end %>
</ul>

app/views/enemies/show.html.erb
<h1><%= @enemy.name %></h1>
<p>Kind: <%= @enemy.kind %></p>
<p>Power Base: <%= @enemy.power_base %></p>
<p>Power Step: <%= @enemy.power_step %></p>
<p>Level: <%= @enemy.level %></p>

app/views/enemies/update.html.erb
<h1>Enemies#update</h1>
<p>Find me in app/views/enemies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStudyRspecWithRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.title %></p>
<% end %>

app/views/weapons/create.html.erb
<h1>Weapons#create</h1>
<p>Find me in app/views/weapons/create.html.erb</p>

app/views/weapons/index.html.erb
<!-- app/views/weapons/index.html.erb -->
<h1>Lista de Armas</h1>

<ul>
  <% @weapons.each do |weapon| %>
    <li>
      <p><strong>Nome:</strong> <%= weapon.name %></p>
      <p><strong>Current Power:</strong> <%= weapon.current_power %></p>
      <p><strong>Título:</strong> <%= weapon.title %></p>
      <p><%= link_to "Detalhes", weapon_path(weapon) %></p>
    </li>
  <% end %>
</ul>

app/views/weapons/show.html.erb
<!-- app/views/weapons/show.html.erb -->

<h1><%= @weapon.name %></h1>
<p><strong>Description:</strong> <%= @weapon.description %></p>
<p><strong>Current Power:</strong> <%= @weapon.current_power %></p>
<p><strong>Power Base:</strong> <%= @weapon.power_base %></p>
<p><strong>Power Step:</strong> <%= @weapon.power_step %></p>
<p><strong>Level:</strong> <%= @weapon.level %></p>